@startuml
class Mascota{
  - salud : int 
    + Comer()
}
class Alimento
class Salud
class Agua
Class Huesos
Class Juguetes
Class Dueño
Class Animal
CLass Casa
Class Ropa

Animal --|> Mascota
Mascota o-- Alimento
Alimento --|> Salud
Dueño *-- Mascota
Mascota *-- Juguetes
Dueño *-- Casa
Mascota *-- Casa
Agua --|> Alimento
Mascota *-- Agua
Mascota o-- Ropa
Dueño*-- Huesos
Mascota*-- Huesos
Dueño o-- Ropa


@enduml